name: Growth

on:
  schedule:
    # UTC 时间 0 点运行一次
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  growth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'

      - name: Depend install and serve
        env:
          COOKIE: ${{ secrets.COOKIE }}
          EMAIL: ${{ secrets.EMAIL }}
          AUTHORIZATION_CODE: ${{ secrets.AUTHORIZATION_CODE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
        run: |
          npm install
          npm run serve
